[theme]
# Primary accent colour for interactive elements.
primarycolor = "#C29AF5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#040404"

# Color used for almost all text.
textColor = "#FAFAFA"

body {
    background-color: #003C7F;
}